// ===== FULL PRICE LIST =====
// Manual price data for all salon services.
// Update prices here without touching any component file.

const priceData = [
  {
    cat: 'Women Hair Cut',
    type: 'single',
    items: [
      ['Hair Cut (Below 12 Years)', '249'],
      ['U/V Cut with Wash', '399'],
      ['Straight Cut with Wash', '349'],
      ['Bangs with Wash', '249'],
      ['Layer Cut with Wash', '699'],
      ['Butterfly Cut with Wash', '799'],
      ['Bob Cut with Wash', '999'],
      ['Hair Wash with Blow Dryer', '299'],
      ['In/Out Dryer', '499'],
      ['Hair Styling', '999'],
    ],
  },
  {
    cat: 'Hair Extensions',
    type: 'single',
    items: [
      ['Hair Extension', '9999+'],
      ['Eyelashes Extension', '1999+'],
    ],
  },
  {
    cat: 'International Hair Colour',
    type: 'single',
    items: [
      ['Majirel Base Touchup', '1499+'],
      ['Fashion Shade Touchup', '1999+'],
      ['Morfose Touchup', '1999+'],
      ['Global Base Color', '2499+'],
      ['Global Fashion Color', '2999+'],
      ['Balayage Color', '7999+'],
      ['Ombre Color', '4999+'],
      ['Highlights (Per Streak)', '299+'],
      ['Highlights', '3999+'],
    ],
  },
  {
    cat: 'Men Hair Cut',
    type: 'single',
    items: [
      ['Hair Cut (Below 12 Years)', '199'],
      ['Hair Cut', '249'],
      ['Hair Setting/Styling', '199'],
      ['Hair Cut + Beard', '349'],
      ['Beard', '149'],
    ],
  },
  {
    cat: 'Waxing',
    type: 'multi',
    cols: ['Normal', 'Rica', 'Premium'],
    items: [
      ['Half Arms',       ['399', '499', '599']],
      ['Half Legs',       ['499', '599', '699']],
      ['Full Arms',       ['599', '799', '999']],
      ['Full Legs',       ['799', '999', '1199']],
      ['Underarms',       ['249', '349', '449']],
      ['Half Back/Front', ['299', '399', '499']],
      ['Full Back/Front', ['599', '699', '799']],
      ['Full Face',       ['299', '399', '499']],
      ['Full Body',       ['2499', '2999', '3499']],
      ['Bikini',          ['999', '1199', '1999']],
    ],
  },
  {
    cat: 'Manicure & Pedicure',
    type: 'multi',
    cols: ['Manicure', 'Pedicure'],
    items: [
      ['Aroma',                    ['-', '-']],
      ['Lotus',                    ['499', '799']],
      ['Sara',                     ['599', '899']],
      ['Raga',                     ['699', '999']],
      ['O3+ Crystal',              ['699', '999']],
      ['Ozone Crystal',            ['1499', '999']],
      ['Lotus Crystal',            ['999', '1999']],
      ['Blossom Kocher Crystal',   ['1299', '1499']],
      ['Ice Cream Premium',        ['1099', '1499']],
      ['Donut & Candy Premium',    ['-', '2299-2499']],
    ],
  },
  {
    cat: 'Nail Art',
    type: 'single',
    items: [
      ['Permanent Nail Polish', '999'],
      ['Acrylic Nail Extension', '1999'],
      ['Gel Nail Extension', '1999'],
      ['French Art', '2499'],
      ['Marble Art', '2499'],
      ['Ombre', '2499'],
      ['Cat Eye', '2999'],
      ['One Finger Glitter', '299'],
      ['One Finger Stone', '299'],
      ['3D Art (One Finger)', '499'],
      ['Bow/Pearl Accessories', '599'],
      ['Chrome Nail Art', '2999'],
      ['Soft Gel Extension', '999'],
    ],
  },
  {
    cat: 'Bleach / D-Tan',
    type: 'single',
    items: [
      ['Sara D-tan', '499'],
      ['Raga D-tan', '499'],
      ['O3+ D-tan', '699'],
      ['Ozone D-tan', '399'],
      ['Oxy Life Bleach', '599'],
      ['Ozone Instant Bleach', '499'],
      ['Fruit Bleach', '399'],
      ['Full Hands Bleach', '599'],
      ['Full Legs Bleach', '799'],
      ['Full Front/Back Bleach', '599'],
      ['Neck Bleach', '399'],
      ['Full Hand D-Tan', '899'],
      ['Full Legs D-Tan', '1299'],
    ],
  },
  {
    cat: 'Polishing / Massage',
    type: 'single',
    items: [
      ['Body Polishing', '3499'],
      ['Body Bleach', '2999'],
      ['Body Massage (Oil/Cream)', '2499'],
      ['Head Massage', '499'],
      ['Foot Massage', '399'],
      ['Full Body D-Tan', '5999'],
    ],
  },
  {
    cat: 'Service Make-up',
    type: 'single',
    items: [
      ['Groom Makeup', '3999+'],
      ['Party Makeup', '3999+'],
      ['Engagement Makeup', '7999+'],
      ['Bridal Makeup', '12999+'],
      ['Air Brush Makeup', '24999+'],
    ],
  },
  {
    cat: 'Clean-up',
    type: 'single',
    items: [
      ['Fruit', '599'],
      ['Sara', '699'],
      ['Raga', '699'],
      ['Lotus Professional', '799'],
      ['O3+', '999'],
    ],
  },
  {
    cat: 'Facial',
    type: 'single',
    items: [
      ['Fruit Facial', '999'],
      ['O3+ Basic', '1499'],
      ['Sara Facial', '1199'],
      ['Raga Facial', '1199'],
      ['Lotus Professional', '1399'],
      ['Skin Glow', '1999'],
      ['Brightening Facial', '2499'],
    ],
  },
  {
    cat: 'Premium Facial',
    type: 'single',
    items: [
      ['Ozone Advance', '3499'],
      ['Kanpeki', '2499'],
      ['Kanpeki Advance', '3499'],
      ['Casmara', '4999'],
      ['Hydra Facial', '1999'],
      ['Hydra Skin Glow', '3499'],
      ['Korean Glass Skin', '3999'],
      ['O3+ Bridal Facial', '2999'],
    ],
  },
  {
    cat: 'Hair Treatments SPA',
    type: 'single',
    items: [
      ["L'Oreal Hair Spa", '999+'],
      ['Dandruff/Hair Fall Spa', '1399+'],
      ['Protein Spa', '1499+'],
      ['Keratin Spa', '1999+'],
      ['Olaplex/Wella Plex/Fiber Plex', '2499+'],
      ['Molecular Spa', '2999+'],
    ],
  },
  {
    cat: 'Special Hair Treatment',
    type: 'single',
    items: [
      ['Anti-Ageing Treatment', '7999+'],
      ['Panthenol Treatment', '8999+'],
      ['IRS Treatment', '4999+'],
      ['Bond Booster', '3999+'],
      ['24K Gold Treatment', '5999+'],
      ['Nano Plastia', '7999+'],
      ['Blue Botox', '6999+'],
      ['GK Keratin Treatment', '5999+'],
      ['Kerashine', '7999+'],
      ['Smoothing/Straight Therapy', '4999+'],
    ],
  },
  {
    cat: 'Threading',
    type: 'multi',
    cols: ['Threading', 'Waxing'],
    items: [
      ['Eyebrows',  ['49', '99']],
      ['Upperlips', ['19', '49']],
      ['Chin',      ['19', '49']],
      ['Side Lock', ['49', '99']],
      ['Forehead',  ['19', '49']],
    ],
  },
];

export default priceData;
